# Generated by Django 5.1.5 on 2025-03-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronunciation', '0002_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='pronunciationrecord',
            name='accuracy',
            field=models.FloatField(default=100.0),
        ),
    ]
