# Generated by Django 5.1.5 on 2025-03-21 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronunciation', '0008_testprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
